export default {
    h1: { fontSize: 18, fontWeight: '400', fontFamily: "UTM Swiss Condensed", fontStyle: "normal", color: "#FFFFFF", lineHeight: 22 },
    h2: { fontSize: 30, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#FFFFFF", lineHeight: 36 },
    h3: { fontSize: 24, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#FFFFFF", lineHeight: 29 },
    h4: { fontSize: 14, fontWeight: '400', fontFamily: "UTM Swiss Condensed", fontStyle: "normal", color: "#FFFFFF", lineHeight: 17 },
    h5: { fontSize: 21, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#FFFFFF", lineHeight: 22 },
    h6: { fontSize: 21, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#0063A7", lineHeight: 22 },
    h7: { fontSize: 25, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#FFFFFF", lineHeight: 29 },
    h8: { fontSize: 14, fontWeight: '400', fontFamily: "UTM Swiss Condensed", fontStyle: "normal", color: "#FFFFFF", lineHeight: 15 },
    h9: { fontSize: 14, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#FFFFFF", lineHeight: 17 },
    h10: { fontSize: 22, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#FFFFFF", lineHeight: 27 },
    h11: { fontSize: 20, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#FFDD00", lineHeight: 22 },
    h12: { fontSize: 18, fontWeight: '400', fontFamily: "UTM Swiss Condensed", fontStyle: "normal", color: "#0063A7", lineHeight: 20 },
    h13: { fontSize: 14, fontWeight: '400', fontFamily: "UTM Swiss Condensed", fontStyle: "normal", color: "#FFDD00", lineHeight: 20 },
    h14: { fontSize: 18, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#FFDD00" },
    h15: { fontSize: 20, fontWeight: '400', fontFamily: "UTM Swiss Condensed", fontStyle: "normal", color: "#2D2D2D", lineHeight: 24 },
    h16: { fontSize: 70, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#005082", lineHeight: 80 },
    h17: { fontSize: 16, fontWeight: '400', fontFamily: "UTM Swiss Condensed", fontStyle: "normal", color: "#000000", lineHeight: 20 },
    h18: { fontSize: 18, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#005082", lineHeight: 20 },
    h19: { fontSize: 18, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#0063A7", lineHeight: 20 },
    h20: { fontSize: 18, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#FFFFFF", lineHeight: 22 },
    h21: { fontSize: 16, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#005082", lineHeight: 20 },
    h22: { fontSize: 17, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#FFFFFF", lineHeight: 17 },
    h23: { fontSize: 18, fontWeight: '900', fontFamily: "UTM Swiss 721 Black Condensed", fontStyle: "normal", color: "#FFFFFF" },


}